name: geopoint3
description: Geospatial data structures. Provides GeoPoint and GeoSerie models.
homepage: https://github.com/mblataric/geopoint2
version: 0.9.1

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  extra_pedantic: ^4.0.0
  latlong2: ^0.9.0
  meta: ^1.9.1
  pedantic: ^1.11.1
  slugify: ^2.0.0

dev_dependencies:
  test: ^1.17.3
